### ISSUE TITLE
Large files take too long to copy

### ISSUE THREAD

**Issue by emuchicken** [emuchicken/pandorytool#1]
*** on usb stick ***
extremely slow copy process/ file access

**Comment by dajoho** [comment]
Not an awful lot I can do here. The code uses native `std::filesystem` calls, which are built right into the compiler and call native windows apis. You could test with another USB stick AND on another PC with the same USB sticks, but I'm betting on just a slow USB interface.

If you have access to a Linux machine with a debian-based distro, such as a raspberry pi, you could test the speed with:

```
sudo apt-get update 
sudo apt-get install ddrescue
lsblk      #to find the device name of the usb stick, such as /dev/sdb99
sudo umount /dev/sdb99
ddrescue /dev/sdb99 /tmp/usbcopy.img
```
This will try and access the USB drive as quickly as possible and will give you some stats about the speed of the interface/usb drive.

**Comment by dajoho** [comment]
Just tested with a USB2 SSD and it finished in seconds. Maybe it really is your USB stick?

**Comment by emuchicken** [comment]
Perhaps. I'll test more tomorrow. On both my main and another usb.

**Comment by dajoho** [comment]
Closing this. It's a foreverissue. USB slow. Harddrive good. #nice.
