### ISSUE TITLE
Descripe your ARSES

### ISSUE THREAD

**Issue by dajoho** [emuchicken/pandorytool#10]
Could you describe where the data for these fields should come from?

![image](https://user-images.githubusercontent.com/952436/74061367-26c86c00-49ec-11ea-86ba-4b52223f34fb.png)

Also.. is `description` (line 4) the same as `detail` (line 19)?

**Comment by dajoho** [comment]
And these ones too:

![image](https://user-images.githubusercontent.com/952436/74067361-5e89e080-49f9-11ea-942c-00dfa881ae2c.png)

ARSEEMUTYPE is the emulator id number, right? How are they meant to look?

**Comment by emuchicken** [comment]
ARSEEMUTYPE is the same as the emutype I gave in the last modeadd.cpp - one sec, if i set arseemutype there, would this... (checkeroony)

**Comment by emuchicken** [comment]
OK - Ive managed to get the emutype working per system type.  Loading time currently works for xml, but not txt  (can you check the code on McGamesTXT.cpp? - seems that the emuLoad variable isnt getting read in mcgamestxt.cpp

**Comment by emuchicken** [comment]
Players can be filled out from the gameslist.xml file  eg: 
 <players>1-4</players>
much how like description was extracted 
Genre we can work out later,  I'll open up a to do later, issue

**Comment by emuchicken** [comment]
bootleg, and language - we can leave.  not needed
