### ISSUE TITLE
Incorrect game title & rom name & syntax

### ISSUE THREAD

**Issue by emuchicken** [emuchicken/pandorytool#11]
The rom name should be like
<rom name="GBC001.gb"/>

![image](https://user-images.githubusercontent.com/45140115/74078816-3ee2ce80-4a72-11ea-98cd-83f3899e9af5.png)

Currently, gives incorrect data:
<rom>Final Fantasy Adventure (USA).gb</rom>
(and also in the description, should have game name)

![image](https://user-images.githubusercontent.com/45140115/74078448-f75a4380-4a6d-11ea-9b87-3bf3e6a0e42c.png)

**Comment by emuchicken** [comment]
Mame titles, almost correct (missing quotes and syntax)

![image](https://user-images.githubusercontent.com/45140115/74078979-620e7d80-4a74-11ea-91fd-27e1d2f33ddd.png)

**Comment by dajoho** [comment]
Think I've fixed the first bug. What's up with the quotes and syntax? What do you mean exactly?

**Comment by emuchicken** [comment]
needs to be <rom name="DC0001.iso"/>  - and not <rom=blah.zip>  - that's all I meant.  Also <name> under translation should be normal standard name of game-  Like <name>Final Fantasy Adventure</name>

**Comment by dajoho** [comment]
Can you try now and see if it does everything you need?

**Comment by emuchicken** [comment]
![image](https://user-images.githubusercontent.com/45140115/74086213-34512500-4ac4-11ea-8091-e466c4181ca2.png)

Should be like this ;-)

**Comment by emuchicken** [comment]
Also at top of file: 
![image](https://user-images.githubusercontent.com/45140115/74086263-8c882700-4ac4-11ea-8118-bc50deeea123.png)

**Comment by emuchicken** [comment]
![image](https://user-images.githubusercontent.com/45140115/74086295-d3761c80-4ac4-11ea-802e-29da4763fb06.png)
In the mcgamestxt file -  the game name doesn't display - should be as above, but outputs as: display name .... With nothing after

**Comment by dajoho** [comment]
Try it again, Sam @emuchicken

**Comment by dajoho** [comment]
@emuchicken Done?
