### ISSUE TITLE
Removing a title will crash tool

### ISSUE THREAD

**Issue by emuchicken** [emuchicken/pandorytool#12]
To replicate: Remove a game iso/rom  run pandory.  As the gameslist.xml points to a blank file, it crashes

Fix: skip game import if not found

![image](https://user-images.githubusercontent.com/45140115/74078889-52db0000-4a73-11ea-998b-36fb25686b24.png)

**Comment by dajoho** [comment]
Before:

copyRomVideoToDestination(absoluteVideoPath, targetRomDir);

You could try adding:

if (!Fs::exists(absoluteVideoPath)) {
  continue;
}
