### ISSUE TITLE
FBA & MAME filenames should not be renamed

### ISSUE THREAD

**Issue by emuchicken** [emuchicken/pandorytool#14]
When these roms are renamed, they become unrecognised by the emulator and do not load. 

So all .zip files from the following directories should NOT be renamed *eg mame190001 etc*;

mame19
mame37
mame78
mame139
fba

**Comment by dajoho** [comment]
@emuchicken Please test. Think I've made the mame games work again.

**Comment by emuchicken** [comment]
Almost there...  
The folders and files created in mcgames should also be the filename (without zip), - so 
If the rom name is *aburner.zip*:::

not:  MAME0001 dir, MAME0001.mp4, MAME0001.xml  

correct: aburner > aburner.mp4, aburner.txt, aburner.xml

Also in the txt:
*display_name aburner*
and in xml
*name ="aburner"*

**Comment by dajoho** [comment]
@emuchicken Check it out.

**Comment by emuchicken** [comment]
Lovely! ;D
