### ISSUE TITLE
Controls configuration fix (for mcgames)

### ISSUE THREAD

**Issue by emuchicken** [emuchicken/pandorytool#17]
![image](https://user-images.githubusercontent.com/45140115/76191695-4d640780-6223-11ea-9c7d-8ac59182b3dc.png)

-PSP- 
We will insert a zip file within the pack.  "PSP settings",  it'll have an MCgames ready to go for the user.  / the PSP0000 folder.
They extract it there, which will install a few controls.ini files (controls0.ini controls1.ini controls2.ini controls3.ini controls4.ini controls5.ini, for example) to the pandora system via mcgames (to encode it)

user installs on their pandora, takes memory card out with encrypted data.
use pandorytool
"pandory pspcontrols -1 -all h:/"
"-1" tells which controls file to use , -1 is controls1.ini
-all tells which roms to work on.  (-all will copy and rename to all directories made by pandory in the ":\data\family\" folder.) *extra games can be added from a pandoryroot/config/pspgamelist.txt file.
h:/ attaches the memory card location.

- With MAME folders *each specific* (mame139, mame078, mame37)

1. *if exists!* COPY file from pandoryroot/config/mame139/*romname*.cfg to MAME139001(gamename) folder
2. if file was copied, - In the XML file add the line <rom name="romname.cfg"/> on the next line under the original game title. eg...
![image](https://user-images.githubusercontent.com/45140115/75839858-26fe3080-5e0d-11ea-9423-44e556979144.png)

**Comment by dajoho** [comment]
This seems a little convoluted. Can we do better somehow?

**Comment by dajoho** [comment]
Done.
