### ISSUE TITLE
Genre additions to game description

### ISSUE THREAD

**Issue by emuchicken** [emuchicken/pandorytool#19]
![image](https://user-images.githubusercontent.com/45140115/75609422-c2607e80-5b4b-11ea-910f-8dc90abee11e.png)

Goal: Pull in genre tag from xml, then fill in genre tag, with a number from 0-6

There are a ton of genres *see above*, so I'd say if it be possible to check through from the start and end of "genre" per game,

![image](https://user-images.githubusercontent.com/45140115/75609479-4fa3d300-5b4c-11ea-8ab3-37a9ea192136.png)

 then when a recognizable phrase is seen, pass on the value of 1-6 to both xml and txt per game.  If phrase isn't there, return with genre of 0 (other)

txt
![image](https://user-images.githubusercontent.com/45140115/75609500-80840800-5b4c-11ea-8c87-a2d3d2bc6b32.png)

xml
![image](https://user-images.githubusercontent.com/45140115/75609512-97c2f580-5b4c-11ea-9d2d-692dfaf01d51.png)

Genre types
0- other
1- fighting
2- action
3- shooting
4- sports
5- puzzle
6- racing

**Comment by dajoho** [comment]
@emuchicken Give it a testaroo.
