### ISSUE TITLE
System names pulled from xml

### ISSUE THREAD

**Issue by emuchicken** [emuchicken/pandorytool#2]
Due to multiple system names
- super famicom - super nintendo - snes
- megadrive - genesis
- turbo graphics - pc engine

... and MAME as a system types in (fba, mame19, mame37, mame139, mame78 etc)

a slight rework is needed.

- rather than pull system type from the xml file,  the system type should be pulled in from the name of the source ROM DIRECTORY-

MAME19, MAME37, MAME139, MAME78 to be added to the original set of
- dreamcast, fba, gba, gbc, megadrive, n64, nes, pcengine, playstation, psp, snes

- remove vanilla "mame" folder

**Comment by dajoho** [comment]
I'll give this back to you to check the system/directory names.

**Comment by dajoho** [comment]
Can this be considered done? @emuchicken

**Comment by dajoho** [comment]
By the way. Directory => System-Mappings are now in src/SystemMapper.cpp
