### ISSUE TITLE
ROM numbering

### ISSUE THREAD

**Issue by dajoho** [emuchicken/pandorytool#24]
Use case: install a few games to test, then install a few more.

With the current numbering scheme, installation A) and B) could contain overlapping ROM numbers, which cause installation to fail. i.e. PSP0001 twice.

We need a way to remember where the use left off and use that numbering. Or similar.

**Comment by dajoho** [comment]
`supercoco` suggests using the date as the name.

**Comment by emuchicken** [comment]
That's not a bad idea.  you'd have to install everything on a different day tho haha
How about date w/ time HHMM ?

**Comment by dajoho** [comment]
Integrated hashing solution to prevent overlap.
