### ISSUE TITLE
Pandora saga box 3000 jailbreak - no changes

### ISSUE THREAD

**Issue by embargoteam** [emuchicken/pandorytool#30]
i jailbreaked my saga box 3000 but i don't have any new option to choose/no access to pure android etc. (pushing 5 x select don't work). It looks like only intro and wallpaper has changed. Is there any hidden command to active ??

**Comment by dajoho** [comment]
Hi. 
Sorry for the delayed response. Github didn't send any notifications. 

Here are two links. I would recommend rejailbreaking with pandory 1.0.8b if you haven't already first. 

https://pg3d-hax.uk/2021/02/05/i-have-just-jailbroken-my-pandora-tv-box-3000-goldensky-3d-but-cannot-get-to-android/

https://pg3d-hax.uk/2021/02/07/how-to-install-android-apps-wirelessly-to-a-pandora-games-3d-console-which-has-been-jailbroken-by-pandory/

We are also a lot quicker to react in our discord, come and visit if you like: https://pg3d-hax.uk/discord.

**Comment by dajoho** [comment]
Also: https://www.youtube.com/watch?v=Y-mSHdqTWbg
