### ISSUE TITLE
pandora 11s pro rrtv

### ISSUE THREAD

**Issue by jadee86** [emuchicken/pandorytool#31]
will this work on the pandora 3d 11s pro  rrtv ???

**Comment by zarecsan** [comment]
También tengo la:
Pandora 3D 11s pro rrtv! 

Espero que nos puedan ayudar!

saludos desde MEXICO!👋🏻

**Comment by dajoho** [comment]
Hi @jadee86  and @zarecsan. There's no support for the 11s at the moment unfortunately.
