### ISSUE TITLE
Can pandory run direct from a usb key andiod native boot like emuelec on a tv andiod box usb hub problem with original firmware

### ISSUE THREAD

**Issue by manboy1212** [emuchicken/pandorytool#32]
Hi I spoke about running amigia uae on andiod version but it won't run because of lack of nand access promission Read Write Execution of the apk settings when you first open the app I know you added retro arch and that does have a emulated core for this and it need the kickstarts bin images aka 3.1 I have this same  issue with Samsung s10 I tried the force access to external sdcard via the delovopment mode but no luck any dev that could help me would  be a bonus

May be the Pandora nand can be piggybacking and hard dumped like a p3 eflasher reprogramed and dumped back on it a raspberry pie gio pins is the main access point
Plus when putting in a hub with 2 separate usb ps2 pads the Pandora firmware thinks a keyboard input works OK with one pad but I think when jamma used this is 2 independent inputs

Regards
Paul

**Comment by dajoho** [comment]
I'm pretty sure it is possible but we haven't managed it yet. Take a look at the Saga 4188 firmware which may be able to boot from SD with a little bit of convincing.

Pop down to the discord if you have further questions, but this is an area we have not explored much.
