### ISSUE TITLE
Problem Scraping rom. Waiting 10 seconds

### ISSUE THREAD

**Issue by kronix2003** [emuchicken/pandorytool#33]
how do i fix this problem?, i was trying to do 3 systems and i got this error. i tought it was because i was using the shareware version, but  after i received it in my email after sending cofee it shows the same error..

i have all the video snaps in the correct folder but im unable to copy them to the usb using pandory tool.

**Comment by emuchicken** [comment]
Register an account at screenscraper.fr then use these details when pandory asks for them.

**Comment by kronix2003** [comment]
Problem solved thanks to your answer
