### ISSUE TITLE
Pandora 9h game limit? 

### ISSUE THREAD

**Issue by kronix2003** [emuchicken/pandorytool#34]
I know that the Pandora 9h has 3288 games,   Is that the game limit? 

my question is that if I can increase that number by removing Chinese etc Roms and adding my own? Or do I have to stick to the number 3288..

thanks!

**Comment by emuchicken** [comment]
No, that's not your limit. - You are mainly limited by the amount of space on the microSD.  If you have any quick questions- please join the Discord- there are many others that also can answer these questions.

**Comment by kronix2003** [comment]
Can you point me into the right direction? I’d like to contribute at least with silly questions which answers will help others on the way

**Comment by emuchicken** [comment]
https://discord.gg/P5Rd99x
