### ISSUE TITLE
No CMakeLists.txt after v1.06

### ISSUE THREAD

**Issue by ricardo85x** [emuchicken/pandorytool#36]
Why the CMakeList.txt was removed after the v1.06?

**Comment by dajoho** [comment]
Hey Richardo. We moved cmakelists out of the folder structure to build other parts of the project. It's now one level up. You should still be able to compile with the older one or just let your IDE create one automatically.

**Comment by ricardo85x** [comment]
I was able to build 1.07 on macOS(11.5) with the previous CMakeList.txt.
but I got a error on 1.08.

I'll try to debug.

Thanks
