### ISSUE TITLE
Missing CMakeLists.txt

### ISSUE THREAD

**Issue by lambage** [emuchicken/pandorytool#37]
The cmake file is missing from the repo.

Also the README.md is missing a partial step.

git clone https://github.com/emuchicken/pandorytool.git
cd pandorytool             <--- this is missing.
mkdir build
cd build
cmake ..

**Comment by dajoho** [comment]
Your IDE should be able to generate it. If not, you just need to compile all the scripts in the src folder as the binary "pandory".

This will be improved in the next version 1.12.
