### ISSUE TITLE
Emulator check

### ISSUE THREAD

**Issue by dajoho** [emuchicken/pandorytool#9]
@emuchicken You had a go at some if/else-Exceptions in ModeAdd.cpp. I have fixed the syntax but don't quite understand exactly what you were trying to do. Could you explain what the logic should be here?

If (GBC) => 14 else 000..... what does that mean exactly?

**Comment by emuchicken** [comment]
I couldnt get it working, so the else statement was to check if anything would override the initial 0
all works now tho- needs checking on wonderswan tho (not tried that system yet!)
